### ISSUE TITLE
HTML to DOCX results in empty DOCX document

### ISSUE THREAD

**Issue by tiblu** [evidenceprime/html-docx-js#19]
Node.JS version: v0.12.7
html-docx-js version: 0.3.0
Tested on: LibreOffice Writer 4.2.8.2, Google Docs, WordPad

**Code**
```
        var fs = require('fs');
        var htmlDocxJs = require('html-docx-js');

        var html = '<!DOCTYPE html><html><head><title>hello!</title></head><body><h1>Hello!</h1></body></html>';
        var docx = htmlDocxJs.asBlob(html);
        fs.writeFileSync('/tmp/test.docx', docx);
```

**Result**
LibreOffice Writer 4.2.8.2, Google Docs, WordPad all display an empty document.

**Notes**

* HTML validates against W3C validator
* Unzipped the file, file contents looks OK
```
➜  /tmp  unzip -l /tmp/test.docx 
Archive:  /tmp/test.docx
  Length      Date    Time    Name
---------  ---------- -----   ----
      465  2015-10-20 17:51   [Content_Types].xml
        0  2015-10-20 17:51   _rels/
      330  2015-10-20 17:51   _rels/.rels
        0  2015-10-20 17:51   word/
     2056  2015-10-20 17:51   word/document.xml
      491  2015-10-20 17:51   word/afchunk.mht
        0  2015-10-20 17:51   word/_rels/
      306  2015-10-20 17:51   word/_rels/document.xml.rels
---------                     -------
     3648                     8 files
```
* ``/tmp/test.docx`` Passes the Open XML validator - http://www.microsoft.com/en-us/download/details.aspx?id=5124
* Unzipped the file and ``afcchunk.mht`` contains the HTML and the HTML validates against W3C validatior
* GitHub won't allow the ``test.docx`` to be uploaded claiming it's not a ``docx``
* Resulting file - http://filebin.ca/2JhttwkoZurM/test.docx

**Comment by N1kto** [comment]
Dear @tiblu , thanks for detailed post.
Unfortunately, as [stated](https://github.com/evidenceprime/html-docx-js#html-docx-js) in README (probably we need to make it more visible) mentioned word processors are not supported. This is not something we can resolve because these word processors do not support the `altchunk` technology which is the core of this lib.

The file you provided is indeed correct. Below is its screenshot from MS Word 2010.

![screenshot from 2015-10-20 21 50 53](https://cloud.githubusercontent.com/assets/5045863/10619262/eed70052-7774-11e5-8894-9a988c02779d.png)

**Comment by tiblu** [comment]
Thank you for your answer. My bad not reading the docs well.
