### ISSUE TITLE
Convert an HTML string to Docx XML

### ISSUE THREAD

**Issue by byrd1089** [evidenceprime/html-docx-js#28]
Hi guys, great library!  

I have a use case where I only need to convert an  HTML string, say a TABLE layout, to an DOCX XML.

var strXml = htmlDocx.convert( strHtml );

Is there a way to do this with your lib?

Thanks,

--Jeff

**Comment by anowak** [comment]
Yes, this is of course possible. The only caveat is that we have chosen to require full HTML document as input to the library. This way it is more flexible, because it can accept any existing document without transforming it to inline CSS styles etc.

For your specific use case, you need to wrap your table in a 'dummy' HTML document.

```
var table = ...
var content = '<!DOCTYPE html><head></head><body>' + table + '</body></html>'
var converted = htmlDocx.asBlob(content, {orientation: orientation});
```
