### ISSUE TITLE
Can it be used with php ?

### ISSUE THREAD

**Issue by tcuer** [evidenceprime/html-docx-js#75]
Hello,

I want to use your library but i'm not on Node.js and i'm using PHP, is it still possible ?

Thznks

**Comment by anowak** [comment]
By going through some hoops, it is possible to execute JavaScript from PHP, but I think it is not worth it.

This library was created in order to be able to generate DOCX documents in the browser (e.g. when offline). As such, it has severe limitations when compared to purely server-side solutions, such as https://github.com/PHPOffice/PHPWord. It needs checking though, if it can convert HTML you have or whether you need to construct the document using their API. The alternative would be to port this library to PHP.
